### ISSUE TITLE
need accurate instruction

### ISSUE THREAD

**Issue by e71828** [tomzaku/Dell-7447-Hackintosh#2]
Thans a lot!
**Dell-7447-Hackintosh/EFI10-15/EFI 2/CLOVER/** and **config 2.plist**,  these  files I tested，battery and adaptor have a bug.

 **Dell-7447-Hackintosh/EFI10-15/EFI 2/CLOVER/** with **config.plist**, the same，no battery or adaptor.

Morever, I found these configurations run faster and smoother than  the other [repo](https://github.com/Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh).

**Comment by tomzaku** [comment]
Sorry, but I don't found any error with battery and adaptor maybe you have to patch dsdt and ssdt
